<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="ODA-L-011" failures="3" tests="7" name="Test" time="50.91" errors="0" timestamp="29 Jul 2018 01:12:41 GMT">
  <testcase classname="testclasses.BrowserTestPOM" name="CartTest" time="32.102"/>
  <testcase classname="testclasses.BrowserTestPOM" name="LoginTestExtended" time="3.549"/>
  <testcase classname="testclasses.CalculationTest" name="TestDevision" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at testclasses.CalculationTest.TestDevision(CalculationTest.java:77)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestDevision -->
  <testcase classname="testclasses.CalculationTest" name="TestMultiply" time="0.005"/>
  <testcase classname="testclasses.CalculationTest" name="TestSubstract" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testclasses.CalculationTest.TestSubstract(CalculationTest.java:58)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestSubstract -->
  <testcase classname="testclasses.CalculationTest" name="TestSum" time="0.003"/>
  <testcase classname="testclasses.BrowserTest" name="LaunchApplication" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testclasses.BrowserTest.LaunchApplication(BrowserTest.java:14)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- LaunchApplication -->
  <testcase classname="testclasses.BaseTest" name="@AfterTest TearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest TearDown -->
  <testcase classname="testclasses.BaseTest" name="@BeforeTest SetUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest SetUp -->
</testsuite> <!-- Test -->
